### ISSUE TITLE
Broken link in repo description

### ISSUE THREAD

**Issue by Kmaschta** [face-orm/face-doc#2]
Hi !

This link http://docs.face-orm.org in the repo description is pointed to the Internet depths.

**Comment by SneakyBobito** [comment]
Hey kma ;)

Indeed ``.org`` is the old one use ``.com`` instead. I just updated it.

If you plan to use it right now, you will prefer wait for the first stable release, a lot of refactoring is on the way. Thought the public api should remain almost the same

**Comment by Kmaschta** [comment]
It's only for satisfy my curiosity about ORM speed.

Thanks a lot!
